name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - run: npm ci
    - run: npm test
      env:
        CI: true
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_BUCKET: ${{ secrets.SUPABASE_BUCKET }}
        COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}